### ISSUE TITLE
HELP: Simple question

### ISSUE THREAD

**Issue by EstherMoellman** [Owyn/Universal_Dark_Theme#1]
Hi @Owyn ,

Firstly, thank you for your script.

I'm trying to test your script with Firefox (Nightly). But I'm failing.
I use this add-on [FireMonkey](https://addons.mozilla.org/en-US/firefox/addon/firemonkey/).
Please, can you help me to install your script in Nightly with this add-on?

Thank you in advance!

**Comment by Owyn** [comment]
Have you tried installing it the usual way? Like you'd do for any other userscripts in Firemonkey?

Opening "raw" link for the .user.js file should start the installation - https://github.com/Owyn/Universal_Dark_Theme/raw/master/uni_dark_theme.user.js 

Though script was only tested in [TamperMonkey](https://www.tampermonkey.net/) it might also work in that Fire one (not guaranteed),
thought TM should be able to accomplish everything Firemonkey can. (Userstyles website has "install style as userscript" button since long ago)

**Comment by EstherMoellman** [comment]
Yeap, I tried many ways, nothing worked for me.
I installed it automatically.
Also manually.
Also raw.
And also I tried manually doing some editions.
I failed.
I'm not sure if I'm doing something wrong, or perhaps is an incompatibility with FireMonkey and your script.

The result is nothing... no pages are dark... no icon, no menu, absolutely nothing happens.
At FireMonkey your script appears as active, but nothing happens.

Any help will be appreciated.
Thanks in advance!

**Comment by Owyn** [comment]
> no icon, no menu

does FireMonkey even has icon and menu support thought? cuz GreaseMonkey doesn't for example.

Quick googling says that "FireMonkey uses Firefox's official API for userscripts and userstyles", meaning it might have far less features (as it always is in official feature implementation - e.g. Google Chrome native userscript support)

I can only suggest trying TamperMonkey as for now

**Comment by EstherMoellman** [comment]
It's working with TamperMonkey, so there is a problem with FireMonkey/Your script.
Please, feel free to close the issue, and thank you.

PS: How can I edit your script, in order to be always dark by default? I don't like to toggle dark theme at each webpage. I prefer dark theme at every webpage by default, and I can add an @exclude at your script whitelisting webpages (dark theme off).

**Comment by Owyn** [comment]
> to be always dark by default?

You'r gonna have a bad time... that's why it's not like that, cuz many sites would look bad or even have features broken

but line 31:
`var cfg_active = (localStorage.getItem('active') === 'true');`
change it to 
`var cfg_active = (localStorage.getItem('active') === null || localStorage.getItem('active') === 'true');`

that should make it active by default

and remove line 62-65 to make it possible to disable script per-site:
```
if(!cfg_active)
		{
			localStorage.removeItem('active');
		}
```
